apiVersion: v1
kind: Pod
metadata:
  name: workload-identity-test
  namespace: image
spec:
  containers:
  - image: google/cloud-sdk:slim
    name: workload-identity-test
    command: ["sleep","infinity"]
    resources:
      limits:
        cpu: "200m"
        memory: "1Gi"     
    securityContext:
      runAsUser: 2000
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - NET_RAW   
  serviceAccountName: ksa-image
