kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: audit-reader-cluster-role-binding
subjects:
- kind: Group
  name: audit@anthos-config-management-demo.com
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: audit-reader-cluster-role
  apiGroup: rbac.authorization.k8s.io