apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
spec:
  replicas: 3
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - image: europe-west2-docker.pkg.dev/ejmadkins-app-ops/remote-registry/hello-world
        name: hello-world
        ports:
        - containerPort: 8080
