apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: hello-vsvc
spec:
  hosts:
  - hello-world.default.svc.cluster.local
  http:
  - name: primary
    route:
    - destination:
        host: rollouts-stable
      weight: 100
    - destination:
        host: rollouts-canary
      weight: 0