kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ops-role-binding
subjects:
- kind: Group
  name: ops@anthos-config-management-demo.com
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: ops-role
  apiGroup: rbac.authorization.k8s.io