apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
spec:
  replicas: 3
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: hello-world
  strategy:
    canary:
      canaryService: hello-world-canary
      stableService: hello-world-stable
      steps:
        - setWeight: 20
        - pause: { duration: 1m }
        - setWeight: 40
        - pause: { duration: 1m }
        - setWeight: 60
        - pause: { duration: 1m }
        - setWeight: 80
        - pause: { duration: 1m }
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - image: europe-west2-docker.pkg.dev/ejmadkins-app-ops/remote-registry/hello-world
        name: hello-world
        ports:
        - containerPort: 8080
