apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: hello-vsvc
spec:
  hosts:
  - hello-world.default.svc.cluster.local
  http:
  - name: primary
    route:
    - destination:
        host: hello-world-stable
      weight: 100
    - destination:
        host: hello-world-canary
      weight: 0