kind: ConfigMap 
apiVersion: v1 
metadata:
  name: cloud-env-configmap
  annotations:
    configmanagement.gke.io/cluster-selector: selector-aws
data:
  environment: AWS-PROD
---
kind: ConfigMap 
apiVersion: v1 
metadata:
  name: cloud-env-configmap
  annotations:
    configmanagement.gke.io/cluster-selector: selector-gcp
data:
  environment: GCP-PROD
---
kind: ConfigMap 
apiVersion: v1 
metadata:
  name: cloud-env-configmap
  annotations:
    configmanagement.gke.io/cluster-selector: selector-gcp-pre-prod
data:
  environment: GCP-PRE-PROD