apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

patchesStrategicMerge:
- rollout.yaml

resources:
- ../../base

configurations:
  - https://argoproj.github.io/argo-rollouts/features/kustomize/rollout-transform.yaml